# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PyQt5\PyQt588\ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(954, 674)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(False)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_date = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_date.setFont(font)
        self.label_date.setObjectName("label_date")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_date)
        self.label_date_c = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_date_c.setFont(font)
        self.label_date_c.setText("")
        self.label_date_c.setObjectName("label_date_c")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_date_c)
        self.label_open = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_open.setFont(font)
        self.label_open.setObjectName("label_open")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_open)
        self.label_open_c = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_open_c.setFont(font)
        self.label_open_c.setText("")
        self.label_open_c.setObjectName("label_open_c")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_open_c)
        self.label_high = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_high.setFont(font)
        self.label_high.setObjectName("label_high")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_high)
        self.label_high_c = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_high_c.setFont(font)
        self.label_high_c.setText("")
        self.label_high_c.setObjectName("label_high_c")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_high_c)
        self.label_low = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_low.setFont(font)
        self.label_low.setObjectName("label_low")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_low)
        self.label_low_c = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_low_c.setFont(font)
        self.label_low_c.setText("")
        self.label_low_c.setObjectName("label_low_c")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_low_c)
        self.label_close = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_close.setFont(font)
        self.label_close.setObjectName("label_close")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_close)
        self.label_close_c = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_close_c.setFont(font)
        self.label_close_c.setText("")
        self.label_close_c.setObjectName("label_close_c")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_close_c)
        self.label_change = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_change.setFont(font)
        self.label_change.setObjectName("label_change")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_change)
        self.label_change_c = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_change_c.setFont(font)
        self.label_change_c.setText("")
        self.label_change_c.setObjectName("label_change_c")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.label_change_c)
        self.verticalLayout_2.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "微信公众号：学点编程吧--汇率走势图"))
        self.label_date.setText(_translate("MainWindow", "日      期："))
        self.label_open.setText(_translate("MainWindow", "开      盘："))
        self.label_high.setText(_translate("MainWindow", "最      高："))
        self.label_low.setText(_translate("MainWindow", "最      低："))
        self.label_close.setText(_translate("MainWindow", "收      盘："))
        self.label_change.setText(_translate("MainWindow", "价格变化："))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

