# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PyQt5\PyQt550\showeather.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Tab(object):
    def setupUi(self, Tab):
        Tab.setObjectName("Tab")
        Tab.resize(372, 275)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_tb = QtWidgets.QLabel(Tab)
        self.label_tb.setText("")
        self.label_tb.setPixmap(QtGui.QPixmap("res/99.png"))
        self.label_tb.setScaledContents(True)
        self.label_tb.setObjectName("label_tb")
        self.horizontalLayout.addWidget(self.label_tb)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.gridLayout.addLayout(self.verticalLayout, 0, 2, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.label_tw = QtWidgets.QLabel(Tab)
        self.label_tw.setText("")
        self.label_tw.setPixmap(QtGui.QPixmap("res/99.png"))
        self.label_tw.setScaledContents(True)
        self.label_tw.setObjectName("label_tw")
        self.horizontalLayout_2.addWidget(self.label_tw)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(Tab)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_wb = QtWidgets.QLabel(Tab)
        self.label_wb.setObjectName("label_wb")
        self.gridLayout.addWidget(self.label_wb, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_wn = QtWidgets.QLabel(Tab)
        self.label_wn.setObjectName("label_wn")
        self.gridLayout.addWidget(self.label_wn, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_tg = QtWidgets.QLabel(Tab)
        self.label_tg.setObjectName("label_tg")
        self.gridLayout.addWidget(self.label_tg, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(Tab)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.label_tl = QtWidgets.QLabel(Tab)
        self.label_tl.setObjectName("label_tl")
        self.gridLayout.addWidget(self.label_tl, 3, 1, 1, 1)
        self.label_fx = QtWidgets.QLabel(Tab)
        self.label_fx.setObjectName("label_fx")
        self.gridLayout.addWidget(self.label_fx, 4, 1, 1, 1)
        self.label_fl = QtWidgets.QLabel(Tab)
        self.label_fl.setObjectName("label_fl")
        self.gridLayout.addWidget(self.label_fl, 5, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)

        self.retranslateUi(Tab)
        QtCore.QMetaObject.connectSlotsByName(Tab)

    def retranslateUi(self, Tab):
        _translate = QtCore.QCoreApplication.translate
        Tab.setWindowTitle(_translate("Tab", "Form"))
        self.label.setText(_translate("Tab", "白天天气："))
        self.label_wb.setText(_translate("Tab", "多云"))
        self.label_2.setText(_translate("Tab", "晚间天气："))
        self.label_wn.setText(_translate("Tab", "多云"))
        self.label_5.setText(_translate("Tab", "风    向："))
        self.label_3.setText(_translate("Tab", "最高温度："))
        self.label_tg.setText(_translate("Tab", "34"))
        self.label_4.setText(_translate("Tab", "最低温度："))
        self.label_6.setText(_translate("Tab", "风    力："))
        self.label_tl.setText(_translate("Tab", "20"))
        self.label_fx.setText(_translate("Tab", "东北"))
        self.label_fl.setText(_translate("Tab", "2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Tab = QtWidgets.QWidget()
    ui = Ui_Tab()
    ui.setupUi(Tab)
    Tab.show()
    sys.exit(app.exec_())

