# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Administrator\Desktop\calculator\calculator_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 500)
        Dialog.setMinimumSize(QtCore.QSize(600, 500))
        Dialog.setMaximumSize(QtCore.QSize(600, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/title/res/calculator.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setSizeGripEnabled(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lcd = QtWidgets.QLCDNumber(Dialog)
        self.lcd.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcd.setDigitCount(8)
        self.lcd.setObjectName("lcd")
        self.verticalLayout_2.addWidget(self.lcd)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.b1 = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Simplified Arabic Fixed")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.b1.setFont(font)
        self.b1.setObjectName("b1")
        self.horizontalLayout.addWidget(self.b1)
        self.b2 = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Simplified Arabic Fixed")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.b2.setFont(font)
        self.b2.setObjectName("b2")
        self.horizontalLayout.addWidget(self.b2)
        self.b3 = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Simplified Arabic Fixed")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.b3.setFont(font)
        self.b3.setObjectName("b3")
        self.horizontalLayout.addWidget(self.b3)
        self.b_plus = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Simplified Arabic Fixed")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.b_plus.setFont(font)
        self.b_plus.setObjectName("b_plus")
        self.horizontalLayout.addWidget(self.b_plus)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.b4 = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Simplified Arabic Fixed")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.b4.setFont(font)
        self.b4.setObjectName("b4")
        self.horizontalLayout_2.addWidget(self.b4)
        self.b5 = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Simplified Arabic Fixed")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.b5.setFont(font)
        self.b5.setObjectName("b5")
        self.horizontalLayout_2.addWidget(self.b5)
        self.b6 = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Simplified Arabic Fixed")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.b6.setFont(font)
        self.b6.setObjectName("b6")
        self.horizontalLayout_2.addWidget(self.b6)
        self.b_sub = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Simplified Arabic Fixed")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.b_sub.setFont(font)
        self.b_sub.setObjectName("b_sub")
        self.horizontalLayout_2.addWidget(self.b_sub)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.b7 = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Simplified Arabic Fixed")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.b7.setFont(font)
        self.b7.setObjectName("b7")
        self.horizontalLayout_3.addWidget(self.b7)
        self.b8 = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Simplified Arabic Fixed")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.b8.setFont(font)
        self.b8.setObjectName("b8")
        self.horizontalLayout_3.addWidget(self.b8)
        self.b9 = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Simplified Arabic Fixed")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.b9.setFont(font)
        self.b9.setObjectName("b9")
        self.horizontalLayout_3.addWidget(self.b9)
        self.b_mul = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Simplified Arabic Fixed")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.b_mul.setFont(font)
        self.b_mul.setObjectName("b_mul")
        self.horizontalLayout_3.addWidget(self.b_mul)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.b0 = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Simplified Arabic Fixed")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.b0.setFont(font)
        self.b0.setObjectName("b0")
        self.horizontalLayout_4.addWidget(self.b0)
        self.point = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Simplified Arabic Fixed")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.point.setFont(font)
        self.point.setObjectName("point")
        self.horizontalLayout_4.addWidget(self.point)
        self.b_clear = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Simplified Arabic Fixed")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.b_clear.setFont(font)
        self.b_clear.setObjectName("b_clear")
        self.horizontalLayout_4.addWidget(self.b_clear)
        self.b_div = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Simplified Arabic Fixed")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.b_div.setFont(font)
        self.b_div.setObjectName("b_div")
        self.horizontalLayout_4.addWidget(self.b_div)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.b_eq = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Simplified Arabic Fixed")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.b_eq.setFont(font)
        self.b_eq.setObjectName("b_eq")
        self.verticalLayout.addWidget(self.b_eq)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "关注微信公众号：学点编程吧--计算器"))
        Dialog.setWhatsThis(_translate("Dialog", "计算器"))
        self.b1.setText(_translate("Dialog", "1"))
        self.b2.setText(_translate("Dialog", "2"))
        self.b3.setText(_translate("Dialog", "3"))
        self.b_plus.setText(_translate("Dialog", "+"))
        self.b4.setText(_translate("Dialog", "4"))
        self.b5.setText(_translate("Dialog", "5"))
        self.b6.setText(_translate("Dialog", "6"))
        self.b_sub.setText(_translate("Dialog", "-"))
        self.b7.setText(_translate("Dialog", "7"))
        self.b8.setText(_translate("Dialog", "8"))
        self.b9.setText(_translate("Dialog", "9"))
        self.b_mul.setText(_translate("Dialog", "*"))
        self.b0.setText(_translate("Dialog", "0"))
        self.point.setText(_translate("Dialog", "."))
        self.b_clear.setText(_translate("Dialog", "清除"))
        self.b_div.setText(_translate("Dialog", "/"))
        self.b_eq.setText(_translate("Dialog", "="))

import calculator_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

